# Generated by Django 5.0.7 on 2024-07-29 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_billingaddress_house_or_road_no'),
        ('users', '0003_remove_profile_area_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_owner', to='users.profile'),
        ),
    ]
