# Generated by Django 5.0.6 on 2024-05-08 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='fish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.category'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='fish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.fish'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='fish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.fish'),
        ),
        migrations.AddField(
            model_name='review',
            name='fish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.fish'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
