# Generated by Django 5.0.7 on 2024-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_remove_order_ordered_items_order_ordered_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered_items',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_items',
            field=models.ManyToManyField(to='market.cartitem'),
        ),
    ]
