# Generated by Django 5.0.6 on 2024-07-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmessage',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
