# Generated by Django 5.0.7 on 2024-07-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_billingaddress_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='house_or_road_no',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
